# 服务器
server:
  # 端口
  port: 8760

# spring 配置
spring:
  application:
    name: thirteen-config
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    # 环境配置 dev（开发环境） test（测试环境） prod（生产环境）
    active: @profile.active@
  # spring cloud 配置
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://gitlab.com/gitlabpeng/spring-cloud-config.git
          # 配置仓库路径
          search-paths: thirteen
          # 访问git仓库的用户名
          username:
          # 访问git仓库的用户密码
          password:
      # 配置仓库的分支
      label: master